set -o vi

alias v="vi"
shopt -s histappend

# search history backward
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'
bind '"^[[15~": "jump\n"'

bind "Control-j":vi-movement-mode
bind "Control-p":history-search-backward
bind "Control-a":beginning-of-line
bind "Control-e":end-of-line
bind "Control-b":backward-word
bind "Control-f":forward-word

export HISTFILESIZE=1000000
export HISTSIZE=1000000

update_prompt() {
    RESET="\[\033[0m\]"           # Reset color
    RED="\[\033[0;31m\]"          # Red
    GREEN="\[\033[0;32m\]"        # Green
    YELLOW="\[\033[0;33m\]"       # Yellow
    BLUE="\[\033[0;34m\]"         # Blue
    PURPLE="\[\033[0;35m\]"       # Purple
    CYAN="\[\033[0;36m\]"         # Cyan
    WHITE="\[\033[1;37m\]"        # White

    # Define the prompt ${TENSORRT_LLM_GIT_COMMIT:0:4} is the important part.
    # It includes first 4 chars of the commit in prompt.
    PS1="$GREEN\u$YELLOW@$RED\h $CYAN\w ${TENSORRT_LLM_GIT_COMMIT:0:4} $RESET\$ "
    history -a
}

PROMPT_COMMAND=update_prompt
export HISTCONTROL=ignorespace:erasedups
export HISTIGNORE="ls:ps:history:pwd"
shopt -s cmdhist

# makefile autocompletion
complete -W "\`grep -oE '^[a-zA-Z0-9_.-]+:([^=]|$)' ?akefile | sed 's/[^a-zA-Z0-9_.-]*$//'\`" make

